#### 1.2 问题

##### 一、安装问题

```python
pcl/visualization/pcl_visualizer.h: 没有那个文件
```

- 是cmake过期的原因，[参考](https://blog.csdn.net/weixin_39750861/article/details/92703412)。解决了问题

  但是camke升级之后，ros有缺损，重新安装ros可解决该问题

  - https://blog.csdn.net/weixin_36628778/article/details/103713866 解决安装很慢的问题
  - http://wiki.ros.org/kinetic/Installation/Ubuntu 官网安装过程

- 缺少[catkin](https://blog.csdn.net/tap880507/article/details/79646913)，当然这里是缺少 catkin_make

  <span style="color:blue;">**总结如下**</span>:

   ```python
  sudo sh -c '. /etc/lsb-release && echo "deb http://mirrors.tuna.tsinghua.edu.cn/ros/ubuntu/ `lsb_release -cs` main" > /etc/apt/sources.list.d/ros-latest.list'
  sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
  curl -sSL 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xC1CF6E31E6BADE8868B172B4F42ED6FBAB17C654' | sudo apt-key add -
  sudo apt-get install ros-kinetic-desktop-full
   ```

```python
source /opt/ros/kinetic/setup.bash /*实际上这一步就可以了*/
echo "source /opt/ros/kinetic/setup.bash" >> ~/.bashrc
source ~/.bashrc
```

- boost[库的重新安装](https://www.cnblogs.com/smallredness/p/9245127.html)，[这里](https://blog.csdn.net/qq_36501182/article/details/79465232)讨论了PCL库与boost库之间的依赖性的问题

- make ros时总是提示：

  ```python
  Target “xxx” links to target "Boost::filesystem" but the target was not found.
  
  CMake Error at CMakeLists.txt:56 (add_executable):
    Target "mynteye_demo" links to target "Boost::filesystem" but the target
    was not found.  Perhaps a find_package() call is missing for an IMPORTED
    target, or an ALIAS target is missing?
  ```

最终导致编译错误：

```python
/usr/bin/ld: 找不到 -lBoost::filesystem
collect2: error: ld returned 1 exit status
CMakeFiles/mynteye_demo.dir/build.make:140: recipe for target 'mynteye_demo' failed
make[2]: *** [mynteye_demo] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mynteye_demo.dir/all' failed
make[1]: *** [CMakeFiles/mynteye_demo.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

我在[这里](https://gitlab.kitware.com/cmake/cmake/issues/17583)找到了答案，主要是没找到Boost::filesystem。<span style='color:red'>这是什么我也不懂</span>，因此对cmakefile进行如下更改：

```python
# Boost_LIBRARIES
find_package(Boost REQUIRED)
find_package(Boost COMPONENTS filesystem thread REQUIRED)
```

当然，我们找到ros下面的cmakelist：(所在位置)

```python
/mnt/hgfs/share/personal/ROS/xiaomi/mynt_eye_sdk/src/MYNT-EYE-S-SDK/wrappers/ros/src/mynt_eye_ros_wrapper
```

- <span style="color:blue;">**在重新编译boost之后，发现SDK又编译不了了**</span>

这一次主要是因为出现SDK需要boost1.72版本。但是我安装的是1.66版本。

![image-20200616081332226](/Users/chenshiming/Library/Application%20Support/typora-user-images/image-20200616081332226.png)

所以用 locate boost 占到了boost1.72的位置，在 `/usr/local/lib/cmake`文件下，删去cmake文件夹，报错解决。删除指令：`sudo rm -rf cmake`

##### 二、启动问题

macos下虚拟机没办法连接相机，因为没有调整UBS连接属性（USB3.0）

##### 三、代码问题

#### 1.3 使用

```python
./samples/_output/bin/get_device_info
```

![20200508161011](https://chendaxiashizhu-1259416116.cos.ap-beijing.myqcloud.com/20200508161011.png)

完成使用。

```python
There are 2 stream requests, select index:
```

调整曝光时间，应该是调整相机的分辨率，或者说是视窗大小。

![image-20200509101850889](/Users/chenshiming/Library/Application%20Support/typora-user-images/image-20200509101850889.png)

> 加速度计：gm/s^2
>
> 陀螺仪：度/s

##### 一、ROS编译运行

- IMU组件的标定

```python
%YAML:1.0
---
version: "1.2"
img_params:
   -
      model: 1
      width: 752
      height: 480
      in_left:
         coeffs: [ -2.2657336134664280e-02, 1.7341970646032978e-03,
             -5.9112834428424067e-03, 1.3875447961473849e-03,
             3.6854145639774879e+02, 3.6838783435247677e+02,
             3.7883175583467153e+02, 2.3705025549869569e+02 ]
      in_right:
         coeffs: [ -1.6961446410338234e-02, -1.5631016454391591e-02,
             1.2334813983377275e-02, -2.8586515100811607e-03,
             3.6763680049316417e+02, 3.6756024079890119e+02,
             3.7570144861915259e+02, 2.3702085562459339e+02 ]
      ex_right_to_left:
         rotation: [ 9.9962856928679333e-01, -3.8640864613998177e-04,
             -2.7250213833964608e-02, 3.4919601901611558e-04,
             9.9999900012050236e-01, -1.3703357748199537e-03,
             2.7250716096625997e-02, 1.3603111238376215e-03,
             9.9962770471104268e-01 ]
         translation: [ -1.2055200987783651e+02, -3.0093663098315021e-01,
             -1.4201461643689612e+00 ]
```

固件升级之后这个问题：

![image-20200520183840961](/Users/chenshiming/Library/Application%20Support/typora-user-images/image-20200520183840961.png)

客服说要用ros自带的opencv，[参考这里](https://blog.csdn.net/u013241583/article/details/98665976)。

报错：

```python
setting /run_id to 10bd2ed4-9af3-11ea-a67c-000c29577f4b
process[rosout-1]: started with pid [90491]
------------------------------------------------------------------
started core service [/rosout]
process[mynteye/mynteye_wrapper_node-2]: started with pid [90508]
[mynteye/mynteye_wrapper_node-2] process has died [pid 90508, exit code -11, cmd /mnt/hgfs/share/personal/ROS/xiaomi/mynt_eye_sdk/devel/lib/mynt_eye_ros_wrapper/mynteye_wrapper_node __name:=mynteye_wrapper_node __log:=/home/chenshiming/.ros/log/10bd2ed4-9af3-11ea-a67c-000c29577f4b/mynteye-mynteye_wrapper_node-2.log].
log file: /home/chenshiming/.ros/log/10bd2ed4-9af3-11ea-a67c-000c29577f4b/mynteye-mynteye_wrapper_node-2*.log
  ----------------
  官网的报错：
  make[3]: *** No rule to make target `/usr/lib/x86_64-linux-gnu/libopencv_videostab.so.2.4.8', needed by `/home/john/Workspace/mynt-eye-s-sdk/wrappers/ros/devel/lib/libmynteye_wrapper.so'.  Stop.
    -------
    没插
    process[mynteye/mynteye_wrapper_node-2]: started with pid [98781]
[mynteye/mynteye_wrapper_node-2] process has died [pid 98781, exit code -11, cmd /mnt/hgfs/share/personal/ROS/xiaomi/mynt_eye_sdk/src/MYNT-EYE-S-SDK/wrappers/ros/devel/lib/mynt_eye_ros_wrapper/mynteye_wrapper_node __name:=mynteye_wrapper_node __log:=/home/chenshiming/.ros/log/b20023d0-9afa-11ea-a67c-000c29577f4b/mynteye-mynteye_wrapper_node-2.log].
log file: /home/chenshiming/.ros/log/b20023d0-9afa-11ea-a67c-000c29577f4b/mynteye-mynteye_wrapper_node-2*.log
  ---
  插了
  process[mynteye/mynteye_wrapper_node-1]: started with pid [99592]
[mynteye/mynteye_wrapper_node-1] process has died [pid 99592, exit code -11, cmd /mnt/hgfs/share/personal/ROS/xiaomi/mynt_eye_sdk/src/MYNT-EYE-S-SDK/wrappers/ros/devel/lib/mynt_eye_ros_wrapper/mynteye_wrapper_node __name:=mynteye_wrapper_node __log:=/home/chenshiming/.ros/log/3ba0d88c-9afb-11ea-a67c-000c29577f4b/mynteye-mynteye_wrapper_node-1.log].
log file: /home/chenshiming/.ros/log/3ba0d88c-9afb-11ea-a67c-000c29577f4b/mynteye-mynteye_wrapper_node-1*.log
```

最后找到原因是在虚拟机里面运行的，难免会出现错误。

运行：

```python
roslaunch mynt_eye_ros_wrapper mynteye.launch
roslaunch mynt_eye_ros_wrapper display.launch
```

#####  二、自带的opencv的测试

- [参考链接](https://blog.csdn.net/yuguo0_331/article/details/82656568)。

ros自带的opencv是3.3.1，我安装的是3.4.1。cmake文件如下：

```python
cmake_minimum_required(VERSION 2.8.3)
project(test1)
set(OpenCV_DIR /opt/ros/kinetic/share/OpenCV-3.3.1-dev)
find_package(catkin REQUIRED COMPONENTS 
  roscpp
  OpenCV
)
message(STATUS "Found OpenCV: ${OpenCV_VERSION}")
include_directories(
 include
  ${catkin_INCLUDE_DIRS}
  ${OpenCV_INCLUDE_DIRS}
)

add_executable(testing src/test.cpp)
target_link_libraries(testing
${catkin_LIBRARIES} 
${OpenCV_LIBRARIES}
)
```

##### 